name: esmith
favicon: null
layout_spectrum: 1
typography_spectrum: 0.03648754511959851
title: A Commitment To You
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e8e6'
    - '#3c3734'
    - '#96775b'
    - '#aba599'
    - '#000000'
  brandStrength: 0.010755624854937196
  lightness: 0.6916834786534309
  saturation: 0.009722667746245861
  rhythmicContrast: 0.43916693329811096
purpose: []
